//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kit.Web.KProduce {
    
    
    /// <summary>
    /// Modify 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Modify {
        	protected global::System.Web.UI.WebControls.Label lblPid;
		protected global::System.Web.UI.WebControls.TextBox txtPname;
		protected global::System.Web.UI.WebControls.TextBox txtPnumber;
		protected global::System.Web.UI.WebControls.TextBox txtPimg;
		protected global::System.Web.UI.WebControls.TextBox txtSpare1;
		protected global::System.Web.UI.WebControls.TextBox txtSpare2;
		protected global::System.Web.UI.WebControls.TextBox txtSpare3;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
