//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kit.Web.Alllog {
    
    
    /// <summary>
    /// Add 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Add 
    {
        
		protected global::System.Web.UI.WebControls.TextBox txtUid;
		protected global::System.Web.UI.WebControls.TextBox txtAtype;
		protected global::System.Web.UI.WebControls.TextBox txtAcontent;
		protected global::System.Web.UI.WebControls.TextBox txtAtime;
		protected global::System.Web.UI.WebControls.TextBox txtAstate;
		protected global::System.Web.UI.WebControls.TextBox txtSpare1;
		protected global::System.Web.UI.WebControls.TextBox txtSpare2;
		protected global::System.Web.UI.WebControls.TextBox txtSpare3;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
