//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kit.Web.KlableroleBase {
    
    
    /// <summary>
    /// Add 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Add 
    {
        
		protected global::System.Web.UI.WebControls.TextBox txtLname;
		protected global::System.Web.UI.WebControls.TextBox txtLcontent;
		protected global::System.Web.UI.WebControls.TextBox txtLcontentsate;
		protected global::System.Web.UI.WebControls.TextBox txtLlabletypeid;
		protected global::System.Web.UI.WebControls.TextBox txtLlabletypename;
		protected global::System.Web.UI.WebControls.TextBox txtLlableImg;
		protected global::System.Web.UI.WebControls.TextBox txtLlableloopid;
		protected global::System.Web.UI.WebControls.TextBox txtLProductid;
		protected global::System.Web.UI.WebControls.TextBox txtLtime;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
