//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kit.Web.KlableroleBase {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblLid;
	protected global::System.Web.UI.WebControls.Label lblLname;
	protected global::System.Web.UI.WebControls.Label lblLcontent;
	protected global::System.Web.UI.WebControls.Label lblLcontentsate;
	protected global::System.Web.UI.WebControls.Label lblLlabletypeid;
	protected global::System.Web.UI.WebControls.Label lblLlabletypename;
	protected global::System.Web.UI.WebControls.Label lblLlableImg;
	protected global::System.Web.UI.WebControls.Label lblLlableloopid;
	protected global::System.Web.UI.WebControls.Label lblLProductid;
	protected global::System.Web.UI.WebControls.Label lblLtime;


       
    }
}
