//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kit.Web.Rrecord {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblRid;
	protected global::System.Web.UI.WebControls.Label lblPid;
	protected global::System.Web.UI.WebControls.Label lblLid;
	protected global::System.Web.UI.WebControls.Label lblRstartnumber;
	protected global::System.Web.UI.WebControls.Label lblRendnumber;
	protected global::System.Web.UI.WebControls.Label lblRprintnum;
	protected global::System.Web.UI.WebControls.Label lblRdatetime;
	protected global::System.Web.UI.WebControls.Label lblUid;
	protected global::System.Web.UI.WebControls.Label lblSpare1;
	protected global::System.Web.UI.WebControls.Label lblSpare2;
	protected global::System.Web.UI.WebControls.Label lblSpare3;


       
    }
}
